#!/bin/bash

set -u

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$TEST_DIR/.." && pwd)"

PASS=0
FAIL=0
TOTAL=0

green() { printf "\033[32m%s\033[0m\n" "$1"; }
red() { printf "\033[31m%s\033[0m\n" "$1"; }
bold() { printf "\033[1m%s\033[0m\n" "$1"; }

pass() {
  green "  PASS: $1"
  PASS=$((PASS + 1))
}

fail() {
  red "  FAIL: $1"
  FAIL=$((FAIL + 1))
}

assert_eq() {
  local description="$1"
  local expected="$2"
  local actual="$3"
  TOTAL=$((TOTAL + 1))

  if [ "$actual" = "$expected" ]; then
    pass "$description"
  else
    fail "$description (expected: $expected, got: $actual)"
  fi
}

assert_contains() {
  local description="$1"
  local haystack="$2"
  local needle="$3"
  TOTAL=$((TOTAL + 1))

  case "$haystack" in
    *"$needle"*) pass "$description" ;;
    *) fail "$description (missing: $needle)" ;;
  esac
}

assert_not_contains() {
  local description="$1"
  local haystack="$2"
  local needle="$3"
  TOTAL=$((TOTAL + 1))

  case "$haystack" in
    *"$needle"*) fail "$description (unexpected: $needle)" ;;
    *) pass "$description" ;;
  esac
}

assert_file_contains() {
  local description="$1"
  local file="$2"
  local needle="$3"
  TOTAL=$((TOTAL + 1))

  if [ -f "$file" ] && grep -Fq "$needle" "$file"; then
    pass "$description"
  else
    fail "$description (missing in $file: $needle)"
  fi
}

assert_exists() {
  local description="$1"
  local path="$2"
  TOTAL=$((TOTAL + 1))

  if [ -e "$path" ] || [ -L "$path" ]; then
    pass "$description"
  else
    fail "$description (missing: $path)"
  fi
}

assert_not_exists() {
  local description="$1"
  local path="$2"
  TOTAL=$((TOTAL + 1))

  if [ ! -e "$path" ] && [ ! -L "$path" ]; then
    pass "$description"
  else
    fail "$description (unexpected path exists: $path)"
  fi
}

assert_symlink_target() {
  local description="$1"
  local link_path="$2"
  local expected_target="$3"
  local actual_target
  TOTAL=$((TOTAL + 1))

  if [ ! -L "$link_path" ]; then
    fail "$description (not a symlink: $link_path)"
    return
  fi

  actual_target="$(readlink "$link_path")"
  if [ "$actual_target" = "$expected_target" ]; then
    pass "$description"
  else
    fail "$description (expected: $expected_target, got: $actual_target)"
  fi
}

finish_tests() {
  echo ""
  bold "=== テスト結果 ==="
  echo "合計: $TOTAL  成功: $PASS  失敗: $FAIL"

  if [ "$FAIL" -eq 0 ]; then
    green "All tests passed!"
    exit 0
  fi

  red "$FAIL test(s) failed."
  exit 1
}

make_dotfiles_fixture() {
  local fixture="$1"

  mkdir -p "$fixture"
  cp "$REPO_DIR/link.sh" "$fixture/link.sh"
  cp "$REPO_DIR/setup.sh" "$fixture/setup.sh"
  chmod +x "$fixture/link.sh" "$fixture/setup.sh"

  printf '# test Brewfile\nbrew "jq"\n' > "$fixture/Brewfile"
  printf '[user]\n    name = Example User\n    email = user@example.com\n' > "$fixture/.gitconfig.local.example"

  mkdir -p "$fixture/.codex"
  {
    printf '# Generated by link.sh from .codex/user-config.toml.template. Do not edit directly.\n'
    printf 'home = "{{HOME}}"\n'
    printf 'dotfile_dir = "{{DOTFILE_DIR}}"\n'
  } > "$fixture/.codex/user-config.toml.template"
  printf 'Codex instructions\n' > "$fixture/.codex/AGENTS.md"

  mkdir -p "$fixture/.claude/scripts"
  printf '{"example": true}\n' > "$fixture/.claude/settings.example.json"
  printf 'Claude instructions\n' > "$fixture/.claude/CLAUDE.md"

  for file in \
    .tmux.conf \
    .zshrc \
    .gitconfig \
    starship.toml \
    commitlint.config.js
  do
    printf 'fixture: %s\n' "$file" > "$fixture/$file"
  done

  for dir in \
    wezterm \
    nvim \
    sheldon \
    yazi \
    aerospace \
    borders \
    sketchybar \
    htop \
    neofetch \
    lazygit
  do
    mkdir -p "$fixture/$dir"
    printf 'fixture: %s\n' "$dir" > "$fixture/$dir/.keep"
  done
}
